<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlumbingSparesSeeder extends Seeder
{
    public function run()
    {
        $items = [
            ['id' => 55, 'name' => 'PVC Pipe 25mm x 3M', 'short_description' => 'PL 25mm PVC Pipe', 'buying_price' => 45.00, 'selling_price' => 70.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-051', 'stock_level' => 20, 'min_level' => 2],
            ['id' => 56, 'name' => 'Copper Pipe 15mm x 2M', 'short_description' => 'PL 15mm Copper Pipe', 'buying_price' => 120.00, 'selling_price' => 180.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-052', 'stock_level' => 10, 'min_level' => 2],
            ['id' => 57, 'name' => 'Elbow 90 Degree 25mm PVC', 'short_description' => 'PL 25mm PVC Elbow', 'buying_price' => 8.00, 'selling_price' => 15.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-053', 'stock_level' => 50, 'min_level' => 2],
            ['id' => 58, 'name' => 'T-Piece 25mm PVC', 'short_description' => 'PL 25mm PVC T-Piece', 'buying_price' => 10.00, 'selling_price' => 18.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-054', 'stock_level' => 45, 'min_level' => 2],
            ['id' => 59, 'name' => 'Stopcock 15mm Brass', 'short_description' => 'PL 15mm Stopcock', 'buying_price' => 75.00, 'selling_price' => 110.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-055', 'stock_level' => 15, 'min_level' => 2],
            ['id' => 60, 'name' => 'Ball Valve 20mm PVC', 'short_description' => 'PL 20mm PVC Ball Valve', 'buying_price' => 30.00, 'selling_price' => 50.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-056', 'stock_level' => 25, 'min_level' => 2],
            ['id' => 61, 'name' => 'Flexi Hose 300mm', 'short_description' => 'PL 300mm Flexi Hose', 'buying_price' => 20.00, 'selling_price' => 35.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-057', 'stock_level' => 30, 'min_level' => 2],
            ['id' => 62, 'name' => 'Sink Mixer Tap', 'short_description' => 'PL Sink Mixer', 'buying_price' => 300.00, 'selling_price' => 450.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-058', 'stock_level' => 8, 'min_level' => 2],
            ['id' => 63, 'name' => 'Basin Mixer Tap', 'short_description' => 'PL Basin Mixer', 'buying_price' => 250.00, 'selling_price' => 380.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-059', 'stock_level' => 7, 'min_level' => 2],
            ['id' => 64, 'name' => 'Toilet Cistern Mechanism', 'short_description' => 'PL Cistern Mech', 'buying_price' => 90.00, 'selling_price' => 130.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-060', 'stock_level' => 12, 'min_level' => 2],
            ['id' => 65, 'name' => 'Toilet Seat Standard', 'short_description' => 'PL Standard Toilet Seat', 'buying_price' => 80.00, 'selling_price' => 120.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-061', 'stock_level' => 18, 'min_level' => 2],
            ['id' => 66, 'name' => 'Waste Trap Sink', 'short_description' => 'PL Sink Trap', 'buying_price' => 35.00, 'selling_price' => 55.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-062', 'stock_level' => 25, 'min_level' => 2],
            ['id' => 67, 'name' => 'Waste Trap Basin', 'short_description' => 'PL Basin Trap', 'buying_price' => 30.00, 'selling_price' => 50.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-063', 'stock_level' => 28, 'min_level' => 2],
            ['id' => 68, 'name' => 'Water Heater Element 3kW', 'short_description' => 'PL 3kW Geyser Element', 'buying_price' => 150.00, 'selling_price' => 220.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-064', 'stock_level' => 5, 'min_level' => 2],
            ['id' => 69, 'name' => 'Pressure Valve 400kPa', 'short_description' => 'PL 400kPa Pressure Valve', 'buying_price' => 200.00, 'selling_price' => 290.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-065', 'stock_level' => 6, 'min_level' => 2],
            ['id' => 70, 'name' => 'Geyser Drain Cock', 'short_description' => 'PL Geyser Drain', 'buying_price' => 40.00, 'selling_price' => 60.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-066', 'stock_level' => 15, 'min_level' => 2],
            ['id' => 71, 'name' => 'Pipe Clip 25mm', 'short_description' => 'PL 25mm Pipe Clip', 'buying_price' => 2.00, 'selling_price' => 5.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-067', 'stock_level' => 100, 'min_level' => 2],
            ['id' => 72, 'name' => 'Thread Seal Tape (PTFE)', 'short_description' => 'PL PTFE Tape', 'buying_price' => 5.00, 'selling_price' => 10.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-068', 'stock_level' => 80, 'min_level' => 2],
            ['id' => 73, 'name' => 'Compression Coupling 15mm', 'short_description' => 'PL 15mm Comp Coupling', 'buying_price' => 25.00, 'selling_price' => 40.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-069', 'stock_level' => 35, 'min_level' => 2],
            ['id' => 74, 'name' => 'Drain Cleaner Liquid 1L', 'short_description' => 'PL Drain Cleaner 1L', 'buying_price' => 60.00, 'selling_price' => 90.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-070', 'stock_level' => 10, 'min_level' => 2],
            ['id' => 75, 'name' => 'Garden Hose 15M', 'short_description' => 'PL 15M Garden Hose', 'buying_price' => 150.00, 'selling_price' => 220.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-071', 'stock_level' => 12, 'min_level' => 2],
            ['id' => 76, 'name' => 'Hose Connector Set', 'short_description' => 'PL Hose Connectors', 'buying_price' => 40.00, 'selling_price' => 65.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-072', 'stock_level' => 20, 'min_level' => 2],
            ['id' => 77, 'name' => 'Shower Head Standard', 'short_description' => 'PL Standard Shower Head', 'buying_price' => 95.00, 'selling_price' => 140.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-073', 'stock_level' => 9, 'min_level' => 2],
            ['id' => 78, 'name' => 'Shower Arm Wall Mount', 'short_description' => 'PL Wall Shower Arm', 'buying_price' => 50.00, 'selling_price' => 75.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-074', 'stock_level' => 11, 'min_level' => 2],
            ['id' => 79, 'name' => 'Toilet Pan Connector', 'short_description' => 'PL Pan Connector', 'buying_price' => 60.00, 'selling_price' => 90.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-075', 'stock_level' => 15, 'min_level' => 2],
            ['id' => 80, 'name' => 'Water Meter 20mm', 'short_description' => 'PL 20mm Water Meter', 'buying_price' => 350.00, 'selling_price' => 500.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-076', 'stock_level' => 3, 'min_level' => 2],
            ['id' => 81, 'name' => 'Tap Washer Assortment', 'short_description' => 'PL Tap Washers', 'buying_price' => 15.00, 'selling_price' => 25.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-077', 'stock_level' => 60, 'min_level' => 2],
            ['id' => 82, 'name' => 'Pipe Wrench 10 Inch', 'short_description' => 'PL 10in Pipe Wrench', 'buying_price' => 180.00, 'selling_price' => 260.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-078', 'stock_level' => 4, 'min_level' => 2],
            ['id' => 83, 'name' => 'Plunger Drain', 'short_description' => 'PL Drain Plunger', 'buying_price' => 40.00, 'selling_price' => 60.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-079', 'stock_level' => 20, 'min_level' => 2],
            ['id' => 84, 'name' => 'Soldering Torch Kit', 'short_description' => 'PL Soldering Torch', 'buying_price' => 220.00, 'selling_price' => 300.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-080', 'stock_level' => 5, 'min_level' => 2],
            ['id' => 85, 'name' => 'Solder Wire Plumbing', 'short_description' => 'PL Plumbing Solder', 'buying_price' => 50.00, 'selling_price' => 80.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-081', 'stock_level' => 25, 'min_level' => 2],
            ['id' => 86, 'name' => 'Flux Paste Plumbing', 'short_description' => 'PL Plumbing Flux', 'buying_price' => 30.00, 'selling_price' => 50.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-082', 'stock_level' => 30, 'min_level' => 2],
            ['id' => 87, 'name' => 'Pipe Cutter 25mm', 'short_description' => 'PL 25mm Pipe Cutter', 'buying_price' => 100.00, 'selling_price' => 150.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-083', 'stock_level' => 8, 'min_level' => 2],
            ['id' => 88, 'name' => 'Isolation Valve 20mm', 'short_description' => 'PL 20mm Isolation Valve', 'buying_price' => 45.00, 'selling_price' => 70.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-084', 'stock_level' => 20, 'min_level' => 2],
            ['id' => 89, 'name' => 'Pressure Reducing Valve', 'short_description' => 'PL Pressure Red Valve', 'buying_price' => 280.00, 'selling_price' => 400.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-085', 'stock_level' => 4, 'min_level' => 2],
            ['id' => 90, 'name' => 'Non-Return Valve 20mm', 'short_description' => 'PL 20mm Non-Return', 'buying_price' => 60.00, 'selling_price' => 90.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-086', 'stock_level' => 12, 'min_level' => 2],
            ['id' => 91, 'name' => 'Basin Waste Pop-Up', 'short_description' => 'PL Pop-Up Waste', 'buying_price' => 70.00, 'selling_price' => 100.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-087', 'stock_level' => 18, 'min_level' => 2],
            ['id' => 92, 'name' => 'Garden Tap Wall Mounted', 'short_description' => 'PL Wall Garden Tap', 'buying_price' => 80.00, 'selling_price' => 120.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-088', 'stock_level' => 15, 'min_level' => 2],
            ['id' => 93, 'name' => 'Drain Rod Set', 'short_description' => 'PL Drain Rods', 'buying_price' => 200.00, 'selling_price' => 290.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-089', 'stock_level' => 3, 'min_level' => 2],
            ['id' => 94, 'name' => 'Pipe Insulation Foam 25mm', 'short_description' => 'PL 25mm Pipe Foam', 'buying_price' => 15.00, 'selling_price' => 25.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-090', 'stock_level' => 40, 'min_level' => 2],
            ['id' => 95, 'name' => 'Adhesive PVC Pipe', 'short_description' => 'PL PVC Adhesive', 'buying_price' => 30.00, 'selling_price' => 50.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-091', 'stock_level' => 25, 'min_level' => 2],
            ['id' => 96, 'name' => 'Rubber Gaskets Assorted', 'short_description' => 'PL Rubber Gaskets', 'buying_price' => 20.00, 'selling_price' => 35.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-092', 'stock_level' => 50, 'min_level' => 2],
            ['id' => 97, 'name' => 'Shower Hose 1.5M', 'short_description' => 'PL 1.5M Shower Hose', 'buying_price' => 55.00, 'selling_price' => 85.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-093', 'stock_level' => 14, 'min_level' => 2],
            ['id' => 98, 'name' => 'Water Connector Braided', 'short_description' => 'PL Braided Connector', 'buying_price' => 30.00, 'selling_price' => 50.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-094', 'stock_level' => 22, 'min_level' => 2],
            ['id' => 99, 'name' => 'Washing Machine Hose', 'short_description' => 'PL Washing Machine Hose', 'buying_price' => 70.00, 'selling_price' => 100.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-095', 'stock_level' => 10, 'min_level' => 2],
            ['id' => 100, 'name' => 'Immersion Heater Spanner', 'short_description' => 'PL Immersion Spanner', 'buying_price' => 85.00, 'selling_price' => 120.00, 'supplier' => 'AquaFlow', 'goods_received_voucher' => 'V20250603-096', 'stock_level' => 6, 'min_level' => 2],
            ['id' => 101, 'name' => 'Sanitary Silicone Sealant', 'short_description' => 'PL Sanitary Silicone', 'buying_price' => 40.00, 'selling_price' => 65.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-097', 'stock_level' => 30, 'min_level' => 2],
            ['id' => 102, 'name' => 'Flexible Coupling Drain', 'short_description' => 'PL Flexible Drain Coupling', 'buying_price' => 90.00, 'selling_price' => 130.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-098', 'stock_level' => 10, 'min_level' => 2],
            ['id' => 103, 'name' => 'Drain Cover Stainless Steel', 'short_description' => 'PL SS Drain Cover', 'buying_price' => 50.00, 'selling_price' => 80.00, 'supplier' => 'Builders Depot', 'goods_received_voucher' => 'V20250603-099', 'stock_level' => 20, 'min_level' => 2],
            ['id' => 104, 'name' => 'Overflow Kit Bath', 'short_description' => 'PL Bath Overflow Kit', 'buying_price' => 65.00, 'selling_price' => 95.00, 'supplier' => 'PlumbMaster', 'goods_received_voucher' => 'V20250603-100', 'stock_level' => 12, 'min_level' => 2],
        ];

        DB::table('inventory')->insert($items);
    }
}